# LAB 6

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../Lab 4/CO2FullData.csv')

In [3]:
df.shape

(7385, 12)

In [4]:
df.head()

,Make,Model,Vehicle Class,ENGINESIZE,CYLINDERS,Transmission,Fuel Type,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,Fuel Consumption Comb (mpg),CO2EMISSIONS
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [5]:
for col in df.columns:
    print(df[col].value_counts())

FORD             628
CHEVROLET        588
BMW              527
MERCEDES-BENZ    419
PORSCHE          376
TOYOTA           330
GMC              328
AUDI             286
NISSAN           259
JEEP             251
DODGE            246
KIA              231
HONDA            214
HYUNDAI          210
MINI             204
VOLKSWAGEN       197
MAZDA            180
LEXUS            178
JAGUAR           160
CADILLAC         158
SUBARU           140
VOLVO            124
INFINITI         108
BUICK            103
RAM               97
LINCOLN           96
MITSUBISHI        95
CHRYSLER          88
LAND ROVER        85
FIAT              73
ACURA             72
MASERATI          61
ROLLS-ROYCE       50
ASTON MARTIN      47
BENTLEY           46
LAMBORGHINI       41
ALFA ROMEO        30
GENESIS           25
SCION             22
SMART              7
BUGATTI            3
SRT                2
Name: Make, dtype: int64
F-150 FFV                    32
F-150 FFV 4X4                32
MUSTANG                      27
FOCUS FFV                    24
F-150 4X4                    20
                             ..
S3 QUATTRO                    1
Palisade AWD                  1
S 63 AMG COUPE                1
AMG GLE 63 S 4MATIC Coupe     1
Sierra LTD 4WD                1
Name: Model, Length: 2053, dtype: int64
SUV - SMALL                 1217
MID-SIZE                    1133
COMPACT                     1022
SUV - STANDARD               735
FULL-SIZE                    639
SUBCOMPACT                   606
PICKUP TRUCK - STANDARD      538
TWO-SEATER                   460
MINICOMPACT                  326
STATION WAGON - SMALL        252
PICKUP TRUCK - SMALL         159
MINIVAN                       80
SPECIAL PURPOSE VEHICLE       77
VAN - PASSENGER               66
STATION WAGON - MID-SIZE      53
VAN - CARGO                   22
Name: Vehicle Class, dtype: int64
2.0    1460
3.0     804
3.6     536
3.5     529
2.5     423
2.4     346
1.6     302
5.3     290
1.8     216
1.4     211
1.5     207
5.0     207
4.0     198
6.2     162
4.4     131
5.7     116
3.8     114
3.7     112
2.7      99
6.0      94
3.3      85
4.7      78
4.3      52
5.5      52
3.4      52
2.3      51
5.2      48
6.4      46
5.6      36
3.2      35
4.6      32
4.8      32
6.6      29
6.7      25
1.2      25
2.8      24
2.9      23
6.5      18
1.0      18
4.2      14
1.3      11
5.4       8
6.8       8
5.9       5
2.1       5
8.4       5
8.0       3
6.3       3
0.9       3
2.2       1
5.8       1
Name: ENGINESIZE, dtype: int64
4     3220
6     2446
8     1402
12     151
3       95
10      42
5       26
16       3
Name: CYLINDERS, dtype: int64
AS6     1324
AS8     1211
M6       901
A6       789
A8       490
AM7      445
A9       339
AS7      319
AV       295
M5       193
AS10     168
AM6      132
AV7      118
AV6      113
M7        91
A5        84
AS9       77
A4        65
AM8       62
A7        53
AV8       39
A10       31
AS5       26
AV10      11
AM5        4
AM9        3
AS4        2
Name: Transmission, dtype: int64
X    3637
Z    3202
E     370
D     175
N       1
Name: Fuel Type, dtype: int64
10.8    125
12.4    123
11.8    120
11.9    119
10.6    109
       ...
6.2       1
21.6      1
23.1      1
26.2      1
23.6      1
Name: FUELCONSUMPTION_CITY, Length: 211, dtype: int64
7.8     209
8.5     184
8.7     169
8.3     168
8.4     162
       ...
17.0      1
19.2      1
15.9      1
4.7       1
19.6      1
Name: FUELCONSUMPTION_HWY, Length: 143, dtype: int64
9.4     145
8.4     136
9.8     135
9.1     132
10.3    130
       ...
19.6      1
19.9      1
21.0      1
6.1       1
20.5      1
Name: FUELCONSUMPTION_COMB, Length: 181, dtype: int64
25    482
29    470
27    461
22    453
26    445
24    399
23    359
31    358
30    333
34    327
20    311
28    310
32    290
21    286
19    265
35    189
33    168
36    163
17    161
18    159
38    147
16    134
37    129
39    101
40     72
15     67
42     45
41     38
43     32
14     30
13     26
50     25
44     16
48     16
47     14
55     12
45     11
60      9
11      8
59      7
12      6
58      6
46      6
49      6
56      5
52      5
63      5
69      4
53      4
51      4
66      2
64      2
54      1
67      1
Name: Fuel Consumption Comb (mpg), dtype: int64
242    85
221    82
214    77
230    77
294    76
       ..
426     1
430     1
450     1
99      1
487     1
Name: CO2EMISSIONS, Length: 331, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
l1 = LabelEncoder()
df['Make'] = l1.fit_transform(df['Make'])
print("Classes of 'Make' column" + str(l1.classes_))
print()

l2 = LabelEncoder()
df['Model'] = l2.fit_transform(df['Model'])
print("Classes of 'Model' column" + str(l2.classes_))
print()

l3 = LabelEncoder()
df['Vehicle Class'] = l3.fit_transform(df['Vehicle Class'])
print("Classes of 'Vehicle Class' column" + str(l3.classes_))
print()

l4 = LabelEncoder()
df['Transmission'] = l4.fit_transform(df['Transmission'])
print("Classes of 'Transmission' column" + str(l4.classes_))
print()

l5 = LabelEncoder()
df['Fuel Type'] = l5.fit_transform(df['Fuel Type'])
print("Classes of 'Fuel Type' column" + str(l5.classes_))
print()

Classes of 'Make' column['ACURA' 'ALFA ROMEO' 'ASTON MARTIN' 'AUDI' 'BENTLEY' 'BMW' 'BUGATTI'
 'BUICK' 'CADILLAC' 'CHEVROLET' 'CHRYSLER' 'DODGE' 'FIAT' 'FORD' 'GENESIS'
 'GMC' 'HONDA' 'HYUNDAI' 'INFINITI' 'JAGUAR' 'JEEP' 'KIA' 'LAMBORGHINI'
 'LAND ROVER' 'LEXUS' 'LINCOLN' 'MASERATI' 'MAZDA' 'MERCEDES-BENZ' 'MINI'
 'MITSUBISHI' 'NISSAN' 'PORSCHE' 'RAM' 'ROLLS-ROYCE' 'SCION' 'SMART' 'SRT'
 'SUBARU' 'TOYOTA' 'VOLKSWAGEN' 'VOLVO']

Classes of 'Model' column['124 SPIDER' '124 Spider' '1500' ... 'tC' 'xB' 'xD']

Classes of 'Vehicle Class' column['COMPACT' 'FULL-SIZE' 'MID-SIZE' 'MINICOMPACT' 'MINIVAN'
 'PICKUP TRUCK - SMALL' 'PICKUP TRUCK - STANDARD'
 'SPECIAL PURPOSE VEHICLE' 'STATION WAGON - MID-SIZE'
 'STATION WAGON - SMALL' 'SUBCOMPACT' 'SUV - SMALL' 'SUV - STANDARD'
 'TWO-SEATER' 'VAN - CARGO' 'VAN - PASSENGER']

Classes of 'Transmission' column['A10' 'A4' 'A5' 'A6' 'A7' 'A8' 'A9' 'AM5' 'AM6' 'AM7' 'AM8' 'AM9' 'AS10'
 'AS4' 'AS5' 'AS6' 'AS7' 'AS8' 'AS9' 'AV' 'AV10' 'AV6' 'AV7' 'AV8' 'M5'
 'M6' 'M7']

Classes of 'Fuel Type' column['D' 'E' 'N' 'X' 'Z']

In [7]:
df.head()

,Make,Model,Vehicle Class,ENGINESIZE,CYLINDERS,Transmission,Fuel Type,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,Fuel Consumption Comb (mpg),CO2EMISSIONS
0,0,1057,0,2.0,4,14,4,9.9,6.7,8.5,33,196
1,0,1057,0,2.4,4,25,4,11.2,7.7,9.6,29,221
2,0,1058,0,1.5,4,22,4,6.0,5.8,5.9,48,136
3,0,1233,11,3.5,6,15,4,12.7,9.1,11.1,25,255
4,0,1499,11,3.5,6,15,4,12.1,8.7,10.6,27,244

In [8]:
X = df.iloc[:,0:11]

In [9]:
X.head()

,Make,Model,Vehicle Class,ENGINESIZE,CYLINDERS,Transmission,Fuel Type,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,Fuel Consumption Comb (mpg)
0,0,1057,0,2.0,4,14,4,9.9,6.7,8.5,33
1,0,1057,0,2.4,4,25,4,11.2,7.7,9.6,29
2,0,1058,0,1.5,4,22,4,6.0,5.8,5.9,48
3,0,1233,11,3.5,6,15,4,12.7,9.1,11.1,25
4,0,1499,11,3.5,6,15,4,12.1,8.7,10.6,27

In [10]:
Y = df.iloc[:,11]

In [11]:
Y.head()

0    196
1    221
2    136
3    255
4    244
Name: CO2EMISSIONS, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size = 0.25)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
X_train

array([[-0.31300232, -0.80981908,  0.95728536, ..., -0.6914295 ,
        -0.81788012,  0.75250365],
       [-0.93277186,  1.13382928,  0.54195798, ..., -1.00642551,
        -1.02605913,  1.02762266],
       [-1.46400289,  0.66923294,  0.95728536, ..., -0.24143519,
        -0.19334309, -0.07285338],
       ...,
       [ 0.1296902 ,  1.2538935 ,  0.95728536, ...,  0.20855912,
        -0.15864659, -0.07285338],
       [ 1.7233833 , -0.82373957, -0.91168785, ..., -1.09642437,
        -1.16484514,  1.30274167],
       [-0.57861784, -0.30172121, -0.08103309, ...,  0.52355513,
         0.43119394, -0.6230914 ]])

In [15]:
# 1. Using the above data build a multi-variable linear regression.
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [16]:
Y_pred = regressor.predict(X_test)

In [17]:
# 2. What is the accuracy level of your model?
from sklearn.metrics import r2_score
score = r2_score(Y_test, Y_pred)
print(score)

0.9122391320501728

In [18]:
# 3. Which attributes have you used in this model?
print("Attributes used to train the model are: ")
print(df.columns.tolist()[0:11])

Attributes used to train the model are:
['Make', 'Model', 'Vehicle Class', 'ENGINESIZE', 'CYLINDERS', 'Transmission', 'Fuel Type', 'FUELCONSUMPTION_CITY', 'FUELCONSUMPTION_HWY', 'FUELCONSUMPTION_COMB', 'Fuel Consumption Comb (mpg)']

In [19]:
# 4. Write your observation/ comment about this data and the model.
# Accuracy of 91.38% is achieved by simply applying Multilinear Regression after scaling and encoding the data.